-- AlterTable
ALTER TABLE "Innings" ADD COLUMN     "currentRunRate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "legalBalls" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "totalBalls" INTEGER NOT NULL DEFAULT 0;
